### ISSUE TITLE
Using this in Docker?

### ISSUE THREAD

**Issue by Austinzveare** [pulento/fixDynamicEQ#1]
Is it possible to run this through Docker for those of us with home servers like Unraid and Truenas? Would love to have this as an Unraid community application instead of running on Windows/Mac.

**Comment by pulento** [comment]
It depends those Unraid/Truenas are Linux on which architecture ?

**Comment by Austinzveare** [comment]
Linux x86/64. The ideal way would be through Docker with a template for this app in the community App Store.

**Comment by pulento** [comment]
I created a Dockerfile and was able to run it copying the manualREW.ady inside the app directory. But I think we need something like a bind mount where your .ADY files is exposed inside the container. So I'll need to make some changes in the code to detect that is running insider a Docker Container and read the file from that mount point.

By now you can try cloning the code and building the container on your own but I get no clue how you can import that to your NAS.

I'll upload the template once I'm sure it is going to work with any .ady users provides.

**Comment by pulento** [comment]
Ok,

Published you can try with the following command:

````
docker run -d -it --mount type=bind,source="$(pwd)"/REW,target=/usr/src/app/rew pulento/fixdynamiceq:0.2.1
````

Please note the "source" parameter that is the directory where your calibration file is (manualREW something) in this case it is just a REW directory inside the current directory you are running the command (pwd command).

**Comment by Austinzveare** [comment]
Thank you! I'll check this out when I get a chance.

**Comment by pulento** [comment]
Ok. Please use the instructions on the README. You need --net=host to allow multicast and also use the latest image which is linux/amd64

**Comment by pulento** [comment]
Going to close this since no feedback.
